var searchData=
[
  ['s_5fspec_0',['S_spec',['../structmfem_1_1TBilinearForm_1_1S__spec.html',1,'mfem::TBilinearForm']]],
  ['saddleschwarzsmoother_1',['SaddleSchwarzSmoother',['../classmfem_1_1blocksolvers_1_1SaddleSchwarzSmoother.html',1,'mfem::blocksolvers']]],
  ['sbm2dirichletintegrator_2',['SBM2DirichletIntegrator',['../classmfem_1_1SBM2DirichletIntegrator.html',1,'mfem']]],
  ['sbm2dirichletlfintegrator_3',['SBM2DirichletLFIntegrator',['../classmfem_1_1SBM2DirichletLFIntegrator.html',1,'mfem']]],
  ['sbm2neumannintegrator_4',['SBM2NeumannIntegrator',['../classmfem_1_1SBM2NeumannIntegrator.html',1,'mfem']]],
  ['sbm2neumannlfintegrator_5',['SBM2NeumannLFIntegrator',['../classmfem_1_1SBM2NeumannLFIntegrator.html',1,'mfem']]],
  ['scalarcrossproductinterpolator_6',['ScalarCrossProductInterpolator',['../classmfem_1_1ScalarCrossProductInterpolator.html',1,'mfem']]],
  ['scalarfiniteelement_7',['ScalarFiniteElement',['../classmfem_1_1ScalarFiniteElement.html',1,'mfem']]],
  ['scalarlayout_8',['ScalarLayout',['../classmfem_1_1ScalarLayout.html',1,'mfem']]],
  ['scalarmatrixproductcoefficient_9',['ScalarMatrixProductCoefficient',['../classmfem_1_1ScalarMatrixProductCoefficient.html',1,'mfem']]],
  ['scalarops_10',['ScalarOps',['../structmfem_1_1ScalarOps.html',1,'mfem']]],
  ['scalarproductinterpolator_11',['ScalarProductInterpolator',['../classmfem_1_1ScalarProductInterpolator.html',1,'mfem']]],
  ['scalarvectorproductcoefficient_12',['ScalarVectorProductCoefficient',['../classmfem_1_1ScalarVectorProductCoefficient.html',1,'mfem']]],
  ['scalarvectorproductinterpolator_13',['ScalarVectorProductInterpolator',['../classmfem_1_1ScalarVectorProductInterpolator.html',1,'mfem']]],
  ['scaledgfcoefficient_14',['ScaledGFCoefficient',['../classmfem_1_1electromagnetics_1_1ScaledGFCoefficient.html',1,'mfem::electromagnetics']]],
  ['scaledoperator_15',['ScaledOperator',['../classmfem_1_1ScaledOperator.html',1,'mfem']]],
  ['scaletransformer_16',['ScaleTransformer',['../classmfem_1_1spde_1_1ScaleTransformer.html',1,'mfem::spde']]],
  ['schrodingerbasekernels_17',['SchrodingerBaseKernels',['../structmfem_1_1SchrodingerBaseKernels.html',1,'mfem']]],
  ['schurconstrainedhypresolver_18',['SchurConstrainedHypreSolver',['../classmfem_1_1SchurConstrainedHypreSolver.html',1,'mfem']]],
  ['schurconstrainedsolver_19',['SchurConstrainedSolver',['../classmfem_1_1SchurConstrainedSolver.html',1,'mfem']]],
  ['screenedpoisson_20',['ScreenedPoisson',['../classmfem_1_1common_1_1ScreenedPoisson.html',1,'mfem::common']]],
  ['sdirk23solver_21',['SDIRK23Solver',['../classmfem_1_1SDIRK23Solver.html',1,'mfem']]],
  ['sdirk33solver_22',['SDIRK33Solver',['../classmfem_1_1SDIRK33Solver.html',1,'mfem']]],
  ['sdirk34solver_23',['SDIRK34Solver',['../classmfem_1_1SDIRK34Solver.html',1,'mfem']]],
  ['secondorderodesolver_24',['SecondOrderODESolver',['../classmfem_1_1SecondOrderODESolver.html',1,'mfem']]],
  ['secondordertimedependentoperator_25',['SecondOrderTimeDependentOperator',['../classmfem_1_1SecondOrderTimeDependentOperator.html',1,'mfem']]],
  ['segment_26',['Segment',['../classmfem_1_1Segment.html',1,'mfem']]],
  ['serialadvectorcgoper_27',['SerialAdvectorCGOper',['../classmfem_1_1SerialAdvectorCGOper.html',1,'mfem']]],
  ['sesquilinearform_28',['SesquilinearForm',['../classmfem_1_1SesquilinearForm.html',1,'mfem']]],
  ['shallowwaterflux_29',['ShallowWaterFlux',['../classmfem_1_1ShallowWaterFlux.html',1,'mfem']]],
  ['shapeevaluator_30',['ShapeEvaluator',['../classmfem_1_1ShapeEvaluator.html',1,'mfem']]],
  ['shapeevaluator_3c_20fe_5ftype_2c_20ir_2c_20real_5ft_20_3e_31',['ShapeEvaluator&lt; FE_type, IR, real_t &gt;',['../classmfem_1_1ShapeEvaluator.html',1,'mfem']]],
  ['shapeevaluator_3c_20meshfe_5ftype_2c_20ir_2c_20real_5ft_20_3e_32',['ShapeEvaluator&lt; meshFE_type, IR, real_t &gt;',['../classmfem_1_1ShapeEvaluator.html',1,'mfem']]],
  ['shapeevaluator_3c_20solfe_5ftype_2c_20ir_2c_20real_5ft_20_3e_33',['ShapeEvaluator&lt; solFE_type, IR, real_t &gt;',['../classmfem_1_1ShapeEvaluator.html',1,'mfem']]],
  ['shapeevaluator_5fbase_34',['ShapeEvaluator_base',['../classmfem_1_1ShapeEvaluator__base.html',1,'mfem']]],
  ['shapeevaluator_5fbase_3c_20fe_2c_20ir_2c_20false_2c_20real_5ft_20_3e_35',['ShapeEvaluator_base&lt; FE, IR, false, real_t &gt;',['../classmfem_1_1ShapeEvaluator__base_3_01FE_00_01IR_00_01false_00_01real__t_01_4.html',1,'mfem']]],
  ['shapeevaluator_5fbase_3c_20fe_2c_20ir_2c_20fe_3a_3atensor_5fprod_20_26_26ir_3a_3atensor_5fprod_2c_20real_5ft_20_3e_36',['ShapeEvaluator_base&lt; FE, IR, FE::tensor_prod &amp;&amp;IR::tensor_prod, real_t &gt;',['../classmfem_1_1ShapeEvaluator__base.html',1,'mfem']]],
  ['shapeevaluator_5fbase_3c_20fe_2c_20ir_2c_20true_2c_20real_5ft_20_3e_37',['ShapeEvaluator_base&lt; FE, IR, true, real_t &gt;',['../classmfem_1_1ShapeEvaluator__base_3_01FE_00_01IR_00_01true_00_01real__t_01_4.html',1,'mfem']]],
  ['shapeevaluator_5fbase_3c_20fe_5ftype_2c_20ir_2c_20fe_5ftype_3a_3atensor_5fprod_20_26_26ir_3a_3atensor_5fprod_2c_20real_5ft_20_3e_38',['ShapeEvaluator_base&lt; FE_type, IR, FE_type::tensor_prod &amp;&amp;IR::tensor_prod, real_t &gt;',['../classmfem_1_1ShapeEvaluator__base.html',1,'mfem']]],
  ['shapeevaluator_5fbase_3c_20meshfe_5ftype_2c_20ir_2c_20meshfe_5ftype_3a_3atensor_5fprod_20_26_26ir_3a_3atensor_5fprod_2c_20real_5ft_20_3e_39',['ShapeEvaluator_base&lt; meshFE_type, IR, meshFE_type::tensor_prod &amp;&amp;IR::tensor_prod, real_t &gt;',['../classmfem_1_1ShapeEvaluator__base.html',1,'mfem']]],
  ['shapeevaluator_5fbase_3c_20solfe_5ftype_2c_20ir_2c_20solfe_5ftype_3a_3atensor_5fprod_20_26_26ir_3a_3atensor_5fprod_2c_20real_5ft_20_3e_40',['ShapeEvaluator_base&lt; solFE_type, IR, solFE_type::tensor_prod &amp;&amp;IR::tensor_prod, real_t &gt;',['../classmfem_1_1ShapeEvaluator__base.html',1,'mfem']]],
  ['sharedmemory_41',['SharedMemory',['../structmfem_1_1future_1_1SharedMemory.html',1,'mfem::future']]],
  ['sharedmemoryinfo_42',['SharedMemoryInfo',['../structmfem_1_1future_1_1SharedMemoryInfo.html',1,'mfem::future']]],
  ['shiftedfacemarker_43',['ShiftedFaceMarker',['../classmfem_1_1ShiftedFaceMarker.html',1,'mfem']]],
  ['shiftedfunctioncoefficient_44',['ShiftedFunctionCoefficient',['../classmfem_1_1ShiftedFunctionCoefficient.html',1,'mfem']]],
  ['shiftedvectorfunctioncoefficient_45',['ShiftedVectorFunctionCoefficient',['../classmfem_1_1ShiftedVectorFunctionCoefficient.html',1,'mfem']]],
  ['sia1solver_46',['SIA1Solver',['../classmfem_1_1SIA1Solver.html',1,'mfem']]],
  ['sia2solver_47',['SIA2Solver',['../classmfem_1_1SIA2Solver.html',1,'mfem']]],
  ['siasolver_48',['SIASolver',['../classmfem_1_1SIASolver.html',1,'mfem']]],
  ['siavsolver_49',['SIAVSolver',['../classmfem_1_1SIAVSolver.html',1,'mfem']]],
  ['sidredatacollection_50',['SidreDataCollection',['../classmfem_1_1SidreDataCollection.html',1,'mfem']]],
  ['simpinterpolationcoefficient_51',['SIMPInterpolationCoefficient',['../classmfem_1_1SIMPInterpolationCoefficient.html',1,'mfem']]],
  ['skewsymmetricvectorconvectionnlfintegrator_52',['SkewSymmetricVectorConvectionNLFIntegrator',['../classmfem_1_1SkewSymmetricVectorConvectionNLFIntegrator.html',1,'mfem']]],
  ['slave_53',['Slave',['../structmfem_1_1NCMesh_1_1Slave.html',1,'mfem::NCMesh']]],
  ['slbqpoptimizer_54',['SLBQPOptimizer',['../classmfem_1_1SLBQPOptimizer.html',1,'mfem']]],
  ['slepceigensolver_55',['SlepcEigenSolver',['../classmfem_1_1SlepcEigenSolver.html',1,'mfem']]],
  ['slisolver_56',['SLISolver',['../classmfem_1_1SLISolver.html',1,'mfem']]],
  ['socketbuf_57',['socketbuf',['../classmfem_1_1socketbuf.html',1,'mfem']]],
  ['socketserver_58',['socketserver',['../classmfem_1_1socketserver.html',1,'mfem']]],
  ['socketstream_59',['socketstream',['../classmfem_1_1socketstream.html',1,'mfem']]],
  ['solver_60',['Solver',['../classmfem_1_1Solver.html',1,'mfem']]],
  ['spacingfunction_61',['SpacingFunction',['../classmfem_1_1SpacingFunction.html',1,'mfem']]],
  ['sparsematrix_62',['SparseMatrix',['../classmfem_1_1SparseMatrix.html',1,'mfem']]],
  ['sparsesmoother_63',['SparseSmoother',['../classmfem_1_1SparseSmoother.html',1,'mfem']]],
  ['spdesolver_64',['SPDESolver',['../classmfem_1_1spde_1_1SPDESolver.html',1,'mfem::spde']]],
  ['spec_65',['Spec',['../structmfem_1_1FieldEvaluator_1_1Spec.html',1,'mfem::FieldEvaluator']]],
  ['specialization_66',['Specialization',['../structmfem_1_1KernelDispatchTable_3_01Kernels_00_01Signature_00_01internal_1_1KernelTypeList_3_09dd34527278f1aaaa8e96381c4910931.html',1,'mfem::KernelDispatchTable&lt; Kernels, Signature, internal::KernelTypeList&lt; Params... &gt;, internal::KernelTypeList&lt; OptParams... &gt; &gt;']]],
  ['sphericalazimuthalcoefficient_67',['SphericalAzimuthalCoefficient',['../classmfem_1_1SphericalAzimuthalCoefficient.html',1,'mfem']]],
  ['sphericalpolarcoefficient_68',['SphericalPolarCoefficient',['../classmfem_1_1SphericalPolarCoefficient.html',1,'mfem']]],
  ['sphericalradialcoefficient_69',['SphericalRadialCoefficient',['../classmfem_1_1SphericalRadialCoefficient.html',1,'mfem']]],
  ['spiraltransformation_70',['SpiralTransformation',['../classmfem_1_1common_1_1SpiralTransformation.html',1,'mfem::common']]],
  ['stable_71',['STable',['../classmfem_1_1STable.html',1,'mfem']]],
  ['stable3d_72',['STable3D',['../classmfem_1_1STable3D.html',1,'mfem']]],
  ['stable3dnode_73',['STable3DNode',['../classmfem_1_1STable3DNode.html',1,'mfem']]],
  ['stack_74',['Stack',['../classmfem_1_1Stack.html',1,'mfem']]],
  ['stack_3c_20elem_20_2a_2c_20num_20_3e_75',['Stack&lt; Elem *, Num &gt;',['../classmfem_1_1Stack.html',1,'mfem']]],
  ['stack_3c_20mfem_3a_3astable3dnode_20_2a_2c_20num_20_3e_76',['Stack&lt; mfem::STable3DNode *, Num &gt;',['../classmfem_1_1Stack.html',1,'mfem']]],
  ['stack_3c_20mfem_3a_3atetrahedron_20_2a_2c_20num_20_3e_77',['Stack&lt; mfem::Tetrahedron *, Num &gt;',['../classmfem_1_1Stack.html',1,'mfem']]],
  ['stack_3c_20node_20_2a_2c_20num_20_3e_78',['Stack&lt; Node *, Num &gt;',['../classmfem_1_1Stack.html',1,'mfem']]],
  ['stackpart_79',['StackPart',['../classmfem_1_1StackPart.html',1,'mfem']]],
  ['stackpart_3c_20mfem_3a_3astable3dnode_20_2a_2c_20num_20_3e_80',['StackPart&lt; mfem::STable3DNode *, Num &gt;',['../classmfem_1_1StackPart.html',1,'mfem']]],
  ['stackpart_3c_20mfem_3a_3atetrahedron_20_2a_2c_20num_20_3e_81',['StackPart&lt; mfem::Tetrahedron *, Num &gt;',['../classmfem_1_1StackPart.html',1,'mfem']]],
  ['stackpart_3c_20node_20_2a_2c_20num_20_3e_82',['StackPart&lt; Node *, Num &gt;',['../classmfem_1_1StackPart.html',1,'mfem']]],
  ['statelessdoftransformation_83',['StatelessDofTransformation',['../classmfem_1_1StatelessDofTransformation.html',1,'mfem']]],
  ['static_5fmethod_5fholder_84',['static_method_holder',['../structstrict__fstream_1_1detail_1_1static__method__holder.html',1,'strict_fstream::detail']]],
  ['staticcondensation_85',['StaticCondensation',['../classmfem_1_1StaticCondensation.html',1,'mfem']]],
  ['stopwatch_86',['StopWatch',['../classmfem_1_1StopWatch.html',1,'mfem']]],
  ['strainenergydensitycoefficient_87',['StrainEnergyDensityCoefficient',['../classmfem_1_1StrainEnergyDensityCoefficient.html',1,'mfem']]],
  ['strict_5ffstream_5fholder_88',['strict_fstream_holder',['../structzstr_1_1detail_1_1strict__fstream__holder.html',1,'zstr::detail']]],
  ['strict_5ffstream_5fholder_3c_20strict_5ffstream_3a_3aifstream_20_3e_89',['strict_fstream_holder&lt; strict_fstream::ifstream &gt;',['../structzstr_1_1detail_1_1strict__fstream__holder.html',1,'zstr::detail']]],
  ['strict_5ffstream_5fholder_3c_20strict_5ffstream_3a_3aofstream_20_3e_90',['strict_fstream_holder&lt; strict_fstream::ofstream &gt;',['../structzstr_1_1detail_1_1strict__fstream__holder.html',1,'zstr::detail']]],
  ['stridedlayout1d_91',['StridedLayout1D',['../structmfem_1_1StridedLayout1D.html',1,'mfem']]],
  ['stridedlayout2d_92',['StridedLayout2D',['../structmfem_1_1StridedLayout2D.html',1,'mfem']]],
  ['stridedlayout2d_3c_20n1_2c_201_2c_20n2_2c_20n1_20_3e_93',['StridedLayout2D&lt; N1, 1, N2, N1 &gt;',['../structmfem_1_1StridedLayout2D.html',1,'mfem']]],
  ['stridedlayout3d_94',['StridedLayout3D',['../structmfem_1_1StridedLayout3D.html',1,'mfem']]],
  ['stridedlayout3d_3c_20n1_2c_201_2c_20n2_2c_20n1_2c_20n3_2c_20n1_20_2an2_20_3e_95',['StridedLayout3D&lt; N1, 1, N2, N1, N3, N1 *N2 &gt;',['../structmfem_1_1StridedLayout3D.html',1,'mfem']]],
  ['stridedlayout4d_96',['StridedLayout4D',['../structmfem_1_1StridedLayout4D.html',1,'mfem']]],
  ['stridedlayout4d_3c_20n1_2c_201_2c_20n2_2c_20n1_2c_20n3_2c_20n1_20_2an2_2c_20n4_2c_20n1_20_2an2_20_2an3_20_3e_97',['StridedLayout4D&lt; N1, 1, N2, N1, N3, N1 *N2, N4, N1 *N2 *N3 &gt;',['../structmfem_1_1StridedLayout4D.html',1,'mfem']]],
  ['strumpackmixedprecisionsolver_98',['STRUMPACKMixedPrecisionSolver',['../classmfem_1_1STRUMPACKMixedPrecisionSolver.html',1,'mfem']]],
  ['strumpackrowlocmatrix_99',['STRUMPACKRowLocMatrix',['../classmfem_1_1STRUMPACKRowLocMatrix.html',1,'mfem']]],
  ['strumpacksolver_100',['STRUMPACKSolver',['../classmfem_1_1STRUMPACKSolver.html',1,'mfem']]],
  ['strumpacksolverbase_101',['STRUMPACKSolverBase',['../classmfem_1_1STRUMPACKSolverBase.html',1,'mfem']]],
  ['strumpacksolverbase_3c_20strumpack_3a_3asparsesolvermixedprecisionmpidist_3c_20float_2c_20double_2c_20hypre_5fbigint_20_3e_20_3e_102',['STRUMPACKSolverBase&lt; strumpack::SparseSolverMixedPrecisionMPIDist&lt; float, double, HYPRE_BigInt &gt; &gt;',['../classmfem_1_1STRUMPACKSolverBase.html',1,'mfem']]],
  ['strumpacksolverbase_3c_20strumpack_3a_3asparsesolvermpidist_3c_20double_2c_20hypre_5fbigint_20_3e_20_3e_103',['STRUMPACKSolverBase&lt; strumpack::SparseSolverMPIDist&lt; double, HYPRE_BigInt &gt; &gt;',['../classmfem_1_1STRUMPACKSolverBase.html',1,'mfem']]],
  ['submesh_104',['SubMesh',['../classmfem_1_1SubMesh.html',1,'mfem']]],
  ['sum_105',['Sum',['../classmfem_1_1future_1_1Sum.html',1,'mfem::future']]],
  ['sumcoefficient_106',['SumCoefficient',['../classmfem_1_1SumCoefficient.html',1,'mfem']]],
  ['sumintegrator_107',['SumIntegrator',['../classmfem_1_1SumIntegrator.html',1,'mfem']]],
  ['sumoperator_108',['SumOperator',['../classmfem_1_1SumOperator.html',1,'mfem']]],
  ['sumreducer_109',['SumReducer',['../structmfem_1_1SumReducer.html',1,'mfem']]],
  ['sundials_110',['Sundials',['../classmfem_1_1Sundials.html',1,'mfem']]],
  ['sundialsmemhelper_111',['SundialsMemHelper',['../classmfem_1_1SundialsMemHelper.html',1,'mfem']]],
  ['sundialsnvector_112',['SundialsNVector',['../classmfem_1_1SundialsNVector.html',1,'mfem']]],
  ['sundialssolver_113',['SundialsSolver',['../classmfem_1_1SundialsSolver.html',1,'mfem']]],
  ['superlurowlocmatrix_114',['SuperLURowLocMatrix',['../classmfem_1_1SuperLURowLocMatrix.html',1,'mfem']]],
  ['superlusolver_115',['SuperLUSolver',['../classmfem_1_1SuperLUSolver.html',1,'mfem']]],
  ['surfacecurrent_116',['SurfaceCurrent',['../classmfem_1_1electromagnetics_1_1SurfaceCurrent.html',1,'mfem::electromagnetics']]],
  ['symdirectsubblocksolver_117',['SymDirectSubBlockSolver',['../classmfem_1_1blocksolvers_1_1SymDirectSubBlockSolver.html',1,'mfem::blocksolvers']]],
  ['symmetricmatrixcoefficient_118',['SymmetricMatrixCoefficient',['../classmfem_1_1SymmetricMatrixCoefficient.html',1,'mfem']]],
  ['symmetricmatrixconstantcoefficient_119',['SymmetricMatrixConstantCoefficient',['../classmfem_1_1SymmetricMatrixConstantCoefficient.html',1,'mfem']]],
  ['symmetricmatrixfunctioncoefficient_120',['SymmetricMatrixFunctionCoefficient',['../classmfem_1_1SymmetricMatrixFunctionCoefficient.html',1,'mfem']]]
];
