var searchData=
[
  ['f_5fasm_5fdata_0',['f_asm_data',['../structmfem_1_1TDiffusionKernel_3_011_00_011_00_01complex__t_01_4_1_1f__asm__data.html',1,'mfem::TDiffusionKernel&lt; 1, 1, complex_t &gt;::f_asm_data&lt; qpts &gt;'],['../structmfem_1_1TDiffusionKernel_3_012_00_012_00_01complex__t_01_4_1_1f__asm__data.html',1,'mfem::TDiffusionKernel&lt; 2, 2, complex_t &gt;::f_asm_data&lt; qpts &gt;'],['../structmfem_1_1TDiffusionKernel_3_013_00_013_00_01complex__t_01_4_1_1f__asm__data.html',1,'mfem::TDiffusionKernel&lt; 3, 3, complex_t &gt;::f_asm_data&lt; qpts &gt;'],['../structmfem_1_1TMassKernel_1_1f__asm__data.html',1,'mfem::TMassKernel&lt; SDim, Dim, complex_t &gt;::f_asm_data&lt; qpts &gt;']]],
  ['fabilinearformextension_1',['FABilinearFormExtension',['../classmfem_1_1FABilinearFormExtension.html',1,'mfem']]],
  ['face_2',['Face',['../structmfem_1_1NCMesh_1_1Face.html',1,'mfem::NCMesh']]],
  ['faceelementtransformations_3',['FaceElementTransformations',['../classmfem_1_1FaceElementTransformations.html',1,'mfem']]],
  ['facegeometricfactors_4',['FaceGeometricFactors',['../classmfem_1_1FaceGeometricFactors.html',1,'mfem']]],
  ['faceinfo_5',['FaceInfo',['../structmfem_1_1Mesh_1_1FaceInfo.html',1,'mfem::Mesh']]],
  ['faceinformation_6',['FaceInformation',['../structmfem_1_1Mesh_1_1FaceInformation.html',1,'mfem::Mesh']]],
  ['faceneighborgeometricfactors_7',['FaceNeighborGeometricFactors',['../classmfem_1_1FaceNeighborGeometricFactors.html',1,'mfem']]],
  ['facequadratureinterpolator_8',['FaceQuadratureInterpolator',['../classmfem_1_1FaceQuadratureInterpolator.html',1,'mfem']]],
  ['facequadraturespace_9',['FaceQuadratureSpace',['../classmfem_1_1FaceQuadratureSpace.html',1,'mfem']]],
  ['facerestriction_10',['FaceRestriction',['../classmfem_1_1FaceRestriction.html',1,'mfem']]],
  ['factors_11',['Factors',['../classmfem_1_1Factors.html',1,'mfem']]],
  ['fcgsolver_12',['FCGSolver',['../classmfem_1_1Ginkgo_1_1FCGSolver.html',1,'mfem::Ginkgo']]],
  ['fdjacobian_13',['FDJacobian',['../classmfem_1_1future_1_1FDJacobian.html',1,'mfem::future']]],
  ['fgmressolver_14',['FGMRESSolver',['../classmfem_1_1FGMRESSolver.html',1,'mfem']]],
  ['fielddescriptor_15',['FieldDescriptor',['../structmfem_1_1future_1_1FieldDescriptor.html',1,'mfem::future']]],
  ['fieldevaluator_16',['FieldEvaluator',['../classmfem_1_1FieldEvaluator.html',1,'mfem']]],
  ['fieldevaluator_5fbase_17',['FieldEvaluator_base',['../classmfem_1_1FieldEvaluator__base.html',1,'mfem']]],
  ['fieldevaluator_5fbase_3c_20fespace_5ft_2c_20veclayout_5ft_2c_20ir_2c_20real_5ft_2c_20real_5ft_20_3e_18',['FieldEvaluator_base&lt; FESpace_t, VecLayout_t, IR, real_t, real_t &gt;',['../classmfem_1_1FieldEvaluator__base.html',1,'mfem']]],
  ['fieldindices_19',['FieldIndices',['../structmfem_1_1navier_1_1NavierParticles_1_1FluidParticleIndices_1_1FieldIndices.html',1,'mfem::navier::NavierParticles::FluidParticleIndices']]],
  ['fieldoperator_20',['FieldOperator',['../classmfem_1_1future_1_1FieldOperator.html',1,'mfem::future']]],
  ['fieldoperator_3c_20_2d1_20_3e_21',['FieldOperator&lt; -1 &gt;',['../classmfem_1_1future_1_1FieldOperator.html',1,'mfem::future']]],
  ['fieldoperator_3c_2d1_20_3e_22',['FieldOperator&lt;-1 &gt;',['../classmfem_1_1future_1_1FieldOperator.html',1,'mfem::future']]],
  ['filteredsolver_23',['FilteredSolver',['../classmfem_1_1FilteredSolver.html',1,'mfem']]],
  ['findpointsgslib_24',['FindPointsGSLIB',['../classmfem_1_1FindPointsGSLIB.html',1,'mfem']]],
  ['findptslocalhashdata_5ft_25',['findptsLocalHashData_t',['../structmfem_1_1gslib_1_1findptsLocalHashData__t.html',1,'mfem::gslib']]],
  ['finiteelement_26',['FiniteElement',['../classmfem_1_1FiniteElement.html',1,'mfem']]],
  ['finiteelementcollection_27',['FiniteElementCollection',['../classmfem_1_1FiniteElementCollection.html',1,'mfem']]],
  ['finiteelementspace_28',['FiniteElementSpace',['../classmfem_1_1FiniteElementSpace.html',1,'mfem']]],
  ['finiteelementspacehierarchy_29',['FiniteElementSpaceHierarchy',['../classmfem_1_1FiniteElementSpaceHierarchy.html',1,'mfem']]],
  ['fluidparticleindices_30',['FluidParticleIndices',['../structmfem_1_1navier_1_1NavierParticles_1_1FluidParticleIndices.html',1,'mfem::navier::NavierParticles']]],
  ['fluxfunction_31',['FluxFunction',['../classmfem_1_1FluxFunction.html',1,'mfem']]],
  ['fmsdatacollection_32',['FMSDataCollection',['../classmfem_1_1FMSDataCollection.html',1,'mfem']]],
  ['forwardeulersolver_33',['ForwardEulerSolver',['../classmfem_1_1ForwardEulerSolver.html',1,'mfem']]],
  ['foxgoodwinsolver_34',['FoxGoodwinSolver',['../classmfem_1_1FoxGoodwinSolver.html',1,'mfem']]],
  ['fstream_35',['fstream',['../classstrict__fstream_1_1fstream.html',1,'strict_fstream']]],
  ['fuentespyramid_36',['FuentesPyramid',['../classmfem_1_1FuentesPyramid.html',1,'mfem']]],
  ['functional_37',['Functional',['../classGecko_1_1Functional.html',1,'Gecko']]],
  ['functionalarithmetic_38',['FunctionalArithmetic',['../classGecko_1_1FunctionalArithmetic.html',1,'Gecko']]],
  ['functionalgeometric_39',['FunctionalGeometric',['../classGecko_1_1FunctionalGeometric.html',1,'Gecko']]],
  ['functionalharmonic_40',['FunctionalHarmonic',['../classGecko_1_1FunctionalHarmonic.html',1,'Gecko']]],
  ['functionalmaximum_41',['FunctionalMaximum',['../classGecko_1_1FunctionalMaximum.html',1,'Gecko']]],
  ['functionalquasiconvex_42',['FunctionalQuasiconvex',['../classGecko_1_1FunctionalQuasiconvex.html',1,'Gecko']]],
  ['functionalrms_43',['FunctionalRMS',['../classGecko_1_1FunctionalRMS.html',1,'Gecko']]],
  ['functionalsmr_44',['FunctionalSMR',['../classGecko_1_1FunctionalSMR.html',1,'Gecko']]],
  ['functioncoefficient_45',['FunctionCoefficient',['../classmfem_1_1FunctionCoefficient.html',1,'mfem']]],
  ['functionsignature_46',['FunctionSignature',['../structmfem_1_1future_1_1FunctionSignature.html',1,'mfem::future']]],
  ['functionsignature_3c_20output_5ft_28input_5fts_2e_2e_2e_29_3e_47',['FunctionSignature&lt; output_t(input_ts...)&gt;',['../structmfem_1_1future_1_1FunctionSignature_3_01output__t_07input__ts_8_8_8_08_4.html',1,'mfem::future']]],
  ['functionspace_48',['FunctionSpace',['../classmfem_1_1FunctionSpace.html',1,'mfem']]]
];
