var searchData=
[
  ['raggeddoftoquad_0',['RaggedDofToQuad',['../classmfem_1_1RaggedDofToQuad.html',1,'mfem']]],
  ['rajacuwrap_1',['RajaCuWrap',['../structmfem_1_1RajaCuWrap.html',1,'mfem']]],
  ['rajacuwrap_3c_201_2c_20max_5fthreads_5fper_5fblock_20_3e_2',['RajaCuWrap&lt; 1, MAX_THREADS_PER_BLOCK &gt;',['../structmfem_1_1RajaCuWrap_3_011_00_01MAX__THREADS__PER__BLOCK_01_4.html',1,'mfem']]],
  ['rajacuwrap_3c_202_2c_200_20_3e_3',['RajaCuWrap&lt; 2, 0 &gt;',['../structmfem_1_1RajaCuWrap_3_012_00_010_01_4.html',1,'mfem']]],
  ['rajacuwrap_3c_202_2c_20max_5fthreads_5fper_5fblock_20_3e_4',['RajaCuWrap&lt; 2, MAX_THREADS_PER_BLOCK &gt;',['../structmfem_1_1RajaCuWrap_3_012_00_01MAX__THREADS__PER__BLOCK_01_4.html',1,'mfem']]],
  ['rajacuwrap_3c_203_2c_200_20_3e_5',['RajaCuWrap&lt; 3, 0 &gt;',['../structmfem_1_1RajaCuWrap_3_013_00_010_01_4.html',1,'mfem']]],
  ['rajacuwrap_3c_203_2c_20max_5fthreads_5fper_5fblock_20_3e_6',['RajaCuWrap&lt; 3, MAX_THREADS_PER_BLOCK &gt;',['../structmfem_1_1RajaCuWrap_3_013_00_01MAX__THREADS__PER__BLOCK_01_4.html',1,'mfem']]],
  ['rajahipwrap_7',['RajaHipWrap',['../structmfem_1_1RajaHipWrap.html',1,'mfem']]],
  ['rajahipwrap_3c_201_2c_20max_5fthreads_5fper_5fblock_20_3e_8',['RajaHipWrap&lt; 1, MAX_THREADS_PER_BLOCK &gt;',['../structmfem_1_1RajaHipWrap_3_011_00_01MAX__THREADS__PER__BLOCK_01_4.html',1,'mfem']]],
  ['rajahipwrap_3c_202_2c_200_20_3e_9',['RajaHipWrap&lt; 2, 0 &gt;',['../structmfem_1_1RajaHipWrap_3_012_00_010_01_4.html',1,'mfem']]],
  ['rajahipwrap_3c_202_2c_20max_5fthreads_5fper_5fblock_20_3e_10',['RajaHipWrap&lt; 2, MAX_THREADS_PER_BLOCK &gt;',['../structmfem_1_1RajaHipWrap_3_012_00_01MAX__THREADS__PER__BLOCK_01_4.html',1,'mfem']]],
  ['rajahipwrap_3c_203_2c_200_20_3e_11',['RajaHipWrap&lt; 3, 0 &gt;',['../structmfem_1_1RajaHipWrap_3_013_00_010_01_4.html',1,'mfem']]],
  ['rajahipwrap_3c_203_2c_20max_5fthreads_5fper_5fblock_20_3e_12',['RajaHipWrap&lt; 3, MAX_THREADS_PER_BLOCK &gt;',['../structmfem_1_1RajaHipWrap_3_013_00_01MAX__THREADS__PER__BLOCK_01_4.html',1,'mfem']]],
  ['rapoperator_13',['RAPOperator',['../classmfem_1_1RAPOperator.html',1,'mfem']]],
  ['ratiocoefficient_14',['RatioCoefficient',['../classmfem_1_1RatioCoefficient.html',1,'mfem']]],
  ['rebalancedofmessage_15',['RebalanceDofMessage',['../classmfem_1_1ParNCMesh_1_1RebalanceDofMessage.html',1,'mfem::ParNCMesh']]],
  ['rebalancemessage_16',['RebalanceMessage',['../classmfem_1_1ParNCMesh_1_1RebalanceMessage.html',1,'mfem::ParNCMesh']]],
  ['rebalancer_17',['Rebalancer',['../classmfem_1_1Rebalancer.html',1,'mfem']]],
  ['recirculationbc_5f2d_18',['RecirculationBC_2D',['../structmfem_1_1navier_1_1NavierParticles_1_1RecirculationBC__2D.html',1,'mfem::navier::NavierParticles']]],
  ['rectangularconstrainedoperator_19',['RectangularConstrainedOperator',['../classmfem_1_1RectangularConstrainedOperator.html',1,'mfem']]],
  ['refinedbilinear2dfiniteelement_20',['RefinedBiLinear2DFiniteElement',['../classmfem_1_1RefinedBiLinear2DFiniteElement.html',1,'mfem']]],
  ['refinedgeometry_21',['RefinedGeometry',['../classmfem_1_1RefinedGeometry.html',1,'mfem']]],
  ['refinedlinear1dfiniteelement_22',['RefinedLinear1DFiniteElement',['../classmfem_1_1RefinedLinear1DFiniteElement.html',1,'mfem']]],
  ['refinedlinear2dfiniteelement_23',['RefinedLinear2DFiniteElement',['../classmfem_1_1RefinedLinear2DFiniteElement.html',1,'mfem']]],
  ['refinedlinear3dfiniteelement_24',['RefinedLinear3DFiniteElement',['../classmfem_1_1RefinedLinear3DFiniteElement.html',1,'mfem']]],
  ['refinedlinearfecollection_25',['RefinedLinearFECollection',['../classmfem_1_1RefinedLinearFECollection.html',1,'mfem']]],
  ['refinedtrilinear3dfiniteelement_26',['RefinedTriLinear3DFiniteElement',['../classmfem_1_1RefinedTriLinear3DFiniteElement.html',1,'mfem']]],
  ['refinement_27',['Refinement',['../structmfem_1_1Refinement.html',1,'mfem']]],
  ['refinementoperator_28',['RefinementOperator',['../classmfem_1_1FiniteElementSpace_1_1RefinementOperator.html',1,'mfem::FiniteElementSpace']]],
  ['reflectionbc_5f2d_29',['ReflectionBC_2D',['../structmfem_1_1navier_1_1NavierParticles_1_1ReflectionBC__2D.html',1,'mfem::navier::NavierParticles']]],
  ['reftrf_30',['RefTrf',['../structmfem_1_1RefTrf.html',1,'mfem']]],
  ['residualbcmonitor_31',['ResidualBCMonitor',['../classmfem_1_1ResidualBCMonitor.html',1,'mfem']]],
  ['residuallogger_32',['ResidualLogger',['../classmfem_1_1Ginkgo_1_1ResidualLogger.html',1,'mfem::Ginkgo']]],
  ['restart_33',['Restart',['../structmfem_1_1VTKHDF_1_1Restart.html',1,'mfem::VTKHDF']]],
  ['restrhash_34',['RestrHash',['../structmfem_1_1ceed_1_1RestrHash.html',1,'mfem::ceed']]],
  ['restrictedcoefficient_35',['RestrictedCoefficient',['../classmfem_1_1RestrictedCoefficient.html',1,'mfem']]],
  ['result_36',['Result',['../structmfem_1_1TElementTransformation_1_1Result.html',1,'mfem::TElementTransformation']]],
  ['result_3c_200_2c_20it_5ft_20_3e_37',['Result&lt; 0, it_t &gt;',['../structmfem_1_1TElementTransformation_1_1Result_3_010_00_01it__t_01_4.html',1,'mfem::TElementTransformation']]],
  ['result_3c_201_2c_20it_5ft_20_3e_38',['Result&lt; 1, it_t &gt;',['../structmfem_1_1TElementTransformation_1_1Result_3_011_00_01it__t_01_4.html',1,'mfem::TElementTransformation']]],
  ['result_3c_2010_2c_20it_5ft_20_3e_39',['Result&lt; 10, it_t &gt;',['../structmfem_1_1TElementTransformation_1_1Result_3_0110_00_01it__t_01_4.html',1,'mfem::TElementTransformation']]],
  ['result_3c_202_2c_20it_5ft_20_3e_40',['Result&lt; 2, it_t &gt;',['../structmfem_1_1TElementTransformation_1_1Result_3_012_00_01it__t_01_4.html',1,'mfem::TElementTransformation']]],
  ['result_3c_203_2c_20it_5ft_20_3e_41',['Result&lt; 3, it_t &gt;',['../structmfem_1_1TElementTransformation_1_1Result_3_013_00_01it__t_01_4.html',1,'mfem::TElementTransformation']]],
  ['result_3c_206_2c_20it_5ft_20_3e_42',['Result&lt; 6, it_t &gt;',['../structmfem_1_1TElementTransformation_1_1Result_3_016_00_01it__t_01_4.html',1,'mfem::TElementTransformation']]],
  ['result_5ft_43',['result_t',['../structmfem_1_1IntRuleCoefficient_1_1Aux_3_01true_00_01dummy_01_4_1_1result__t.html',1,'mfem::IntRuleCoefficient::Aux&lt; true, dummy &gt;']]],
  ['rk2solver_44',['RK2Solver',['../classmfem_1_1RK2Solver.html',1,'mfem']]],
  ['rk3sspsolver_45',['RK3SSPSolver',['../classmfem_1_1RK3SSPSolver.html',1,'mfem']]],
  ['rk4solver_46',['RK4Solver',['../classmfem_1_1RK4Solver.html',1,'mfem']]],
  ['rk6solver_47',['RK6Solver',['../classmfem_1_1RK6Solver.html',1,'mfem']]],
  ['rk8solver_48',['RK8Solver',['../classmfem_1_1RK8Solver.html',1,'mfem']]],
  ['rottrilinearhexfiniteelement_49',['RotTriLinearHexFiniteElement',['../classmfem_1_1RotTriLinearHexFiniteElement.html',1,'mfem']]],
  ['rowiterator_50',['RowIterator',['../classmfem_1_1DSTable_1_1RowIterator.html',1,'mfem::DSTable']]],
  ['rownode_51',['RowNode',['../classmfem_1_1RowNode.html',1,'mfem']]],
  ['rt0_5f2dfecollection_52',['RT0_2DFECollection',['../classmfem_1_1RT0__2DFECollection.html',1,'mfem']]],
  ['rt0_5f3dfecollection_53',['RT0_3DFECollection',['../classmfem_1_1RT0__3DFECollection.html',1,'mfem']]],
  ['rt0hexfiniteelement_54',['RT0HexFiniteElement',['../classmfem_1_1RT0HexFiniteElement.html',1,'mfem']]],
  ['rt0pyrfiniteelement_55',['RT0PyrFiniteElement',['../classmfem_1_1RT0PyrFiniteElement.html',1,'mfem']]],
  ['rt0quadfiniteelement_56',['RT0QuadFiniteElement',['../classmfem_1_1RT0QuadFiniteElement.html',1,'mfem']]],
  ['rt0tetfiniteelement_57',['RT0TetFiniteElement',['../classmfem_1_1RT0TetFiniteElement.html',1,'mfem']]],
  ['rt0trianglefiniteelement_58',['RT0TriangleFiniteElement',['../classmfem_1_1RT0TriangleFiniteElement.html',1,'mfem']]],
  ['rt0wdgfiniteelement_59',['RT0WdgFiniteElement',['../classmfem_1_1RT0WdgFiniteElement.html',1,'mfem']]],
  ['rt1_5f2dfecollection_60',['RT1_2DFECollection',['../classmfem_1_1RT1__2DFECollection.html',1,'mfem']]],
  ['rt1_5f3dfecollection_61',['RT1_3DFECollection',['../classmfem_1_1RT1__3DFECollection.html',1,'mfem']]],
  ['rt1hexfiniteelement_62',['RT1HexFiniteElement',['../classmfem_1_1RT1HexFiniteElement.html',1,'mfem']]],
  ['rt1quadfiniteelement_63',['RT1QuadFiniteElement',['../classmfem_1_1RT1QuadFiniteElement.html',1,'mfem']]],
  ['rt1trianglefiniteelement_64',['RT1TriangleFiniteElement',['../classmfem_1_1RT1TriangleFiniteElement.html',1,'mfem']]],
  ['rt2_5f2dfecollection_65',['RT2_2DFECollection',['../classmfem_1_1RT2__2DFECollection.html',1,'mfem']]],
  ['rt2quadfiniteelement_66',['RT2QuadFiniteElement',['../classmfem_1_1RT2QuadFiniteElement.html',1,'mfem']]],
  ['rt2trianglefiniteelement_67',['RT2TriangleFiniteElement',['../classmfem_1_1RT2TriangleFiniteElement.html',1,'mfem']]],
  ['rt_5ffecollection_68',['RT_FECollection',['../classmfem_1_1RT__FECollection.html',1,'mfem']]],
  ['rt_5ffespace_69',['RT_FESpace',['../classmfem_1_1common_1_1RT__FESpace.html',1,'mfem::common']]],
  ['rt_5ffuentespyramidelement_70',['RT_FuentesPyramidElement',['../classmfem_1_1RT__FuentesPyramidElement.html',1,'mfem']]],
  ['rt_5fhexahedronelement_71',['RT_HexahedronElement',['../classmfem_1_1RT__HexahedronElement.html',1,'mfem']]],
  ['rt_5fparfespace_72',['RT_ParFESpace',['../classmfem_1_1common_1_1RT__ParFESpace.html',1,'mfem::common']]],
  ['rt_5fquadrilateralelement_73',['RT_QuadrilateralElement',['../classmfem_1_1RT__QuadrilateralElement.html',1,'mfem']]],
  ['rt_5fr1d_5ffecollection_74',['RT_R1D_FECollection',['../classmfem_1_1RT__R1D__FECollection.html',1,'mfem']]],
  ['rt_5fr1d_5fsegmentelement_75',['RT_R1D_SegmentElement',['../classmfem_1_1RT__R1D__SegmentElement.html',1,'mfem']]],
  ['rt_5fr2d_5ffecollection_76',['RT_R2D_FECollection',['../classmfem_1_1RT__R2D__FECollection.html',1,'mfem']]],
  ['rt_5fr2d_5ffiniteelement_77',['RT_R2D_FiniteElement',['../classmfem_1_1RT__R2D__FiniteElement.html',1,'mfem']]],
  ['rt_5fr2d_5fquadrilateralelement_78',['RT_R2D_QuadrilateralElement',['../classmfem_1_1RT__R2D__QuadrilateralElement.html',1,'mfem']]],
  ['rt_5fr2d_5fsegmentelement_79',['RT_R2D_SegmentElement',['../classmfem_1_1RT__R2D__SegmentElement.html',1,'mfem']]],
  ['rt_5fr2d_5ftrace_5ffecollection_80',['RT_R2D_Trace_FECollection',['../classmfem_1_1RT__R2D__Trace__FECollection.html',1,'mfem']]],
  ['rt_5fr2d_5ftriangleelement_81',['RT_R2D_TriangleElement',['../classmfem_1_1RT__R2D__TriangleElement.html',1,'mfem']]],
  ['rt_5ftetrahedronelement_82',['RT_TetrahedronElement',['../classmfem_1_1RT__TetrahedronElement.html',1,'mfem']]],
  ['rt_5ftrace_5ffecollection_83',['RT_Trace_FECollection',['../classmfem_1_1RT__Trace__FECollection.html',1,'mfem']]],
  ['rt_5ftriangleelement_84',['RT_TriangleElement',['../classmfem_1_1RT__TriangleElement.html',1,'mfem']]],
  ['rt_5fwedgeelement_85',['RT_WedgeElement',['../classmfem_1_1RT__WedgeElement.html',1,'mfem']]],
  ['rusanovflux_86',['RusanovFlux',['../classmfem_1_1RusanovFlux.html',1,'mfem']]]
];
