var searchData=
[
  ['eabilinearformextension_0',['EABilinearFormExtension',['../classmfem_1_1EABilinearFormExtension.html',1,'mfem']]],
  ['edge_1',['Edge',['../classmfem_1_1Edge.html',1,'mfem']]],
  ['elasticitycomponentintegrator_2',['ElasticityComponentIntegrator',['../classmfem_1_1ElasticityComponentIntegrator.html',1,'mfem']]],
  ['elasticitydiagonalpreconditioner_3',['ElasticityDiagonalPreconditioner',['../classmfem_1_1ElasticityDiagonalPreconditioner.html',1,'mfem']]],
  ['elasticitygradientoperator_4',['ElasticityGradientOperator',['../classmfem_1_1ElasticityGradientOperator.html',1,'mfem']]],
  ['elasticityintegrator_5',['ElasticityIntegrator',['../classmfem_1_1ElasticityIntegrator.html',1,'mfem']]],
  ['elasticityoperator_6',['ElasticityOperator',['../classmfem_1_1ElasticityOperator.html',1,'mfem']]],
  ['element_7',['Element',['../classmfem_1_1Element.html',1,'mfem::Element'],['../structmfem_1_1NCMesh_1_1Element.html',1,'mfem::NCMesh::Element']]],
  ['elementdofindexer_8',['ElementDofIndexer',['../classmfem_1_1ElementDofIndexer.html',1,'mfem']]],
  ['elementmeshstream_9',['ElementMeshStream',['../classmfem_1_1common_1_1ElementMeshStream.html',1,'mfem::common']]],
  ['elementrankandattribute_10',['ElementRankAndAttribute',['../structmfem_1_1ParNCMesh_1_1ElementRankAndAttribute.html',1,'mfem::ParNCMesh']]],
  ['elementrestriction_11',['ElementRestriction',['../classmfem_1_1ElementRestriction.html',1,'mfem']]],
  ['elementrestrictionoperator_12',['ElementRestrictionOperator',['../classmfem_1_1ElementRestrictionOperator.html',1,'mfem']]],
  ['elementset_13',['ElementSet',['../classmfem_1_1ParNCMesh_1_1ElementSet.html',1,'mfem::ParNCMesh']]],
  ['elementtransformation_14',['ElementTransformation',['../classmfem_1_1ElementTransformation.html',1,'mfem']]],
  ['elementvaluemessage_15',['ElementValueMessage',['../classmfem_1_1ParNCMesh_1_1ElementValueMessage.html',1,'mfem::ParNCMesh']]],
  ['elementvaluemessage_3c_20elementrankandattribute_2c_20false_2c_20varmessagetag_3a_3aneighbor_5felement_5frank_5fvm_20_3e_16',['ElementValueMessage&lt; ElementRankAndAttribute, false, VarMessageTag::NEIGHBOR_ELEMENT_RANK_VM &gt;',['../classmfem_1_1ParNCMesh_1_1ElementValueMessage.html',1,'mfem::ParNCMesh']]],
  ['elementvaluemessage_3c_20elementrankandattribute_2c_20true_2c_20varmessagetag_3a_3arebalance_5fvm_20_3e_17',['ElementValueMessage&lt; ElementRankAndAttribute, true, VarMessageTag::REBALANCE_VM &gt;',['../classmfem_1_1ParNCMesh_1_1ElementValueMessage.html',1,'mfem::ParNCMesh']]],
  ['elementvaluemessage_3c_20int_2c_20false_2c_20varmessagetag_3a_3aneighbor_5fderefinement_5fvm_20_3e_18',['ElementValueMessage&lt; int, false, VarMessageTag::NEIGHBOR_DEREFINEMENT_VM &gt;',['../classmfem_1_1ParNCMesh_1_1ElementValueMessage.html',1,'mfem::ParNCMesh']]],
  ['elementvaluemessage_3c_20int_2c_20false_2c_20varmessagetag_3a_3aneighbor_5fprefinement_5fvm_20_3e_19',['ElementValueMessage&lt; int, false, VarMessageTag::NEIGHBOR_PREFINEMENT_VM &gt;',['../classmfem_1_1ParNCMesh_1_1ElementValueMessage.html',1,'mfem::ParNCMesh']]],
  ['elementvaluemessage_3c_20neighborrefinement_2c_20false_2c_20varmessagetag_3a_3aneighbor_5frefinement_5fvm_20_3e_20',['ElementValueMessage&lt; NeighborRefinement, false, VarMessageTag::NEIGHBOR_REFINEMENT_VM &gt;',['../classmfem_1_1ParNCMesh_1_1ElementValueMessage.html',1,'mfem::ParNCMesh']]],
  ['eliminationcgsolver_21',['EliminationCGSolver',['../classmfem_1_1EliminationCGSolver.html',1,'mfem']]],
  ['eliminationgmressolver_22',['EliminationGMRESSolver',['../classmfem_1_1EliminationGMRESSolver.html',1,'mfem']]],
  ['eliminationprojection_23',['EliminationProjection',['../classmfem_1_1EliminationProjection.html',1,'mfem']]],
  ['eliminationsolver_24',['EliminationSolver',['../classmfem_1_1EliminationSolver.html',1,'mfem']]],
  ['eliminator_25',['Eliminator',['../classmfem_1_1Eliminator.html',1,'mfem']]],
  ['embedding_26',['Embedding',['../structmfem_1_1Embedding.html',1,'mfem']]],
  ['enableconvergencelogger_27',['EnableConvergenceLogger',['../classmfem_1_1Ginkgo_1_1EnableConvergenceLogger.html',1,'mfem::Ginkgo']]],
  ['enableginkgosolver_28',['EnableGinkgoSolver',['../classmfem_1_1Ginkgo_1_1EnableGinkgoSolver.html',1,'mfem::Ginkgo']]],
  ['enableginkgosolver_3c_20gko_3a_3asolver_3a_3abicgstab_3c_20real_5ft_20_3e_20_3e_29',['EnableGinkgoSolver&lt; gko::solver::Bicgstab&lt; real_t &gt; &gt;',['../classmfem_1_1Ginkgo_1_1EnableGinkgoSolver.html',1,'mfem::Ginkgo']]],
  ['enableginkgosolver_3c_20gko_3a_3asolver_3a_3acbgmres_3c_20real_5ft_20_3e_20_3e_30',['EnableGinkgoSolver&lt; gko::solver::CbGmres&lt; real_t &gt; &gt;',['../classmfem_1_1Ginkgo_1_1EnableGinkgoSolver.html',1,'mfem::Ginkgo']]],
  ['enableginkgosolver_3c_20gko_3a_3asolver_3a_3acg_3c_20real_5ft_20_3e_20_3e_31',['EnableGinkgoSolver&lt; gko::solver::Cg&lt; real_t &gt; &gt;',['../classmfem_1_1Ginkgo_1_1EnableGinkgoSolver.html',1,'mfem::Ginkgo']]],
  ['enableginkgosolver_3c_20gko_3a_3asolver_3a_3acgs_3c_20real_5ft_20_3e_20_3e_32',['EnableGinkgoSolver&lt; gko::solver::Cgs&lt; real_t &gt; &gt;',['../classmfem_1_1Ginkgo_1_1EnableGinkgoSolver.html',1,'mfem::Ginkgo']]],
  ['enableginkgosolver_3c_20gko_3a_3asolver_3a_3afcg_3c_20real_5ft_20_3e_20_3e_33',['EnableGinkgoSolver&lt; gko::solver::Fcg&lt; real_t &gt; &gt;',['../classmfem_1_1Ginkgo_1_1EnableGinkgoSolver.html',1,'mfem::Ginkgo']]],
  ['enableginkgosolver_3c_20gko_3a_3asolver_3a_3agmres_3c_20real_5ft_20_3e_20_3e_34',['EnableGinkgoSolver&lt; gko::solver::Gmres&lt; real_t &gt; &gt;',['../classmfem_1_1Ginkgo_1_1EnableGinkgoSolver.html',1,'mfem::Ginkgo']]],
  ['enableginkgosolver_3c_20gko_3a_3asolver_3a_3air_3c_20real_5ft_20_3e_20_3e_35',['EnableGinkgoSolver&lt; gko::solver::Ir&lt; real_t &gt; &gt;',['../classmfem_1_1Ginkgo_1_1EnableGinkgoSolver.html',1,'mfem::Ginkgo']]],
  ['enableresiduallogger_36',['EnableResidualLogger',['../classmfem_1_1Ginkgo_1_1EnableResidualLogger.html',1,'mfem::Ginkgo']]],
  ['entity_37',['Entity',['../structmfem_1_1MeshPart_1_1Entity.html',1,'mfem::MeshPart']]],
  ['entityhelper_38',['EntityHelper',['../structmfem_1_1MeshPart_1_1EntityHelper.html',1,'mfem::MeshPart']]],
  ['errorestimator_39',['ErrorEstimator',['../classmfem_1_1ErrorEstimator.html',1,'mfem']]],
  ['errorexception_40',['ErrorException',['../classmfem_1_1ErrorException.html',1,'mfem']]],
  ['esdirk32solver_41',['ESDIRK32Solver',['../classmfem_1_1ESDIRK32Solver.html',1,'mfem']]],
  ['esdirk33solver_42',['ESDIRK33Solver',['../classmfem_1_1ESDIRK33Solver.html',1,'mfem']]],
  ['eulerflux_43',['EulerFlux',['../classmfem_1_1EulerFlux.html',1,'mfem']]],
  ['exception_44',['Exception',['../classstrict__fstream_1_1Exception.html',1,'strict_fstream::Exception'],['../classzstr_1_1Exception.html',1,'zstr::Exception']]],
  ['explicitrksolver_45',['ExplicitRKSolver',['../classmfem_1_1ExplicitRKSolver.html',1,'mfem']]],
  ['exponentialmatrixcoefficient_46',['ExponentialMatrixCoefficient',['../classmfem_1_1ExponentialMatrixCoefficient.html',1,'mfem']]],
  ['extrapolator_47',['Extrapolator',['../classmfem_1_1Extrapolator.html',1,'mfem']]],
  ['extrudecoefficient_48',['ExtrudeCoefficient',['../classmfem_1_1ExtrudeCoefficient.html',1,'mfem']]]
];
